### ISSUE TITLE
Question about showing code chunks in text

### ISSUE THREAD

**Issue by abduazizR** [kelly-sovacool/rackham#2]
Hi

First of all, thank you so much for making this available. I mainly write my manuscripts in quarto, and it was unfortunate for me when I found that writing a well-formatted thesis is not as easy as writing manuscripts. My knowledge of LaTex is really modest. Thanks to you, I still hope to write my thesis with Quarto. Hopefully, by the end, I can put a Quarto template for my university.

I have a question regarding including R code chunks inside the dissertation. I managed to make the code output appear without warnings or messages, but I cannot make the code chunks to show up.

Any ideas on how to solve this

Thanks.

**Comment by kelly-sovacool** [comment]
Have you tried setting `echo: true` for the code chunks you want to show? 
https://quarto.org/docs/computations/execution-options.html

**Comment by abduazizR** [comment]
Thanks for the quick response. I tried doing that but it gave the following error

```
ERROR: 
compilation failed- error
LaTeX Error: Environment Shaded undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.390 \begin{Shaded}
```

**Comment by abduazizR** [comment]
I found a solution [here](https://stackoverflow.com/questions/41052687/rstudio-pdf-knit-fails-with-environment-shaded-undefined-error). 

Basically, the user will need to add the following lines to `template.tex`

```
$if(highlighting-macros)$
$highlighting-macros$
$endif$
```

**Comment by kelly-sovacool** [comment]
Thanks for finding a solution! I think it’d be a good addition to the
template. Feel free to open a PR if you’d like.
